########################################################################
#                                                                      #
#      __  __ _                            __ _                        #
#     |  \/  (_)                          / _| |                       #
#     | \  / |_ _ __   ___  ___ _ __ __ _| |_| |_   ___  ___ ___       #
#     | |\/| | | '_ \ / _ \/ __| '__/ _` |  _| __| / _ \/ __/ _ \      #
#     | |  | | | | | |  __/ (__| | | (_| | | | |_ |  __/ (_| (_) |     #
#     |_|  |_|_|_| |_|\___|\___|_|  \__,_|_|  \__(_)___|\___\___/      #
#                                                                      #
#                                                                      #
#                             MINECRAFT.ECO                            #
#                                                                      #
########################################################################

apiKey: "" # Сюда вставьте токен вашего сервера (Узнать: minecraft.eco > личный кабинет > токен плагина)

design:
  title: "§0ᴍɪɴᴇᴄʀᴀꜰᴛ.ᴇᴄᴏ"
  successBuyIcon:
    material: GREEN_DYE
  notEnoughVotesMessages:
    - ""
    - "§4 [✘] §cНедостаточно голосов"
    - "§f Баланс голосов: §6{votes}"
    - "§f Получить голоса §7↓"
    - "§a Minecraft.eco/mc-servers/YourDomainIP/vote"
    - ""
  notEnoughVotesIcon:
    name: "§4[✘] §cНедостаточно голосов"
    material: barrier
    lore:
      - '&fПолучите голоса по ссылке в чате!'
  productSlots: [10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43] # Слоты для наград
  inventory:
    nextPage:
      slot: 50
      icon:
        name: "§6Следующая страница §7»"
        material: ARROW
    prevPage:
      slot: 48
      icon:
        name: "§7« §6Предыдущая страница"
        material: ARROW
    glass1:
      slot: 0
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass2:
      slot: 1
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass3:
      slot: 2
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass4:
      slot: 3
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    sign:
      slot: 4
      clickCommand:
        - "tell:&e[☆] §fПолучить голоса§7:"
        - "tell:§aMinecraft.eco/mc-servers/YourDomainIP/vote"
      icon:
        name: "&eКак получить голоса?"
        material: DARK_OAK_SIGN
        lore:
          - "&71) &6Нажмите&f, чтобы получить ссылку"
          - "&72) &fПерейдите по ней для &6голосования"
          - "&73) &6Проголосуйте"
          - "&74) &fИ получите &6&nголос"
          - ""
          - "&e[☆] &fБаланс голосов: &6&l{votes}"
          - ""
    glass5:
      slot: 5
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass6:
      slot: 6
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass7:
      slot: 7
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass8:
      slot: 8
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass9:
      slot: 9
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass10:
      slot: 17
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass11:
      slot: 18
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass12:
      slot: 26
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass13:
      slot: 27
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass14:
      slot: 35
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass15:
      slot: 36
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass16:
      slot: 44
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass17:
      slot: 45
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass18:
      slot: 46
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass19:
      slot: 47
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass20:
      slot: 49
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass21:
      slot: 51
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass22:
      slot: 52
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
    glass23:
      slot: 53
      icon:
        name: " "
        material: ORANGE_STAINED_GLASS_PANE
products:
  item1: # Пример как добавить текстуру на голову
    price: 1
    icon:
      name: "§eДонат-кейс"
      material: PLAYER_HEAD
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjU0NGIwOWQ1NTljZWJiNDA2YjcyMjcwMGYzYmQzN2NiMTZkMjhkMmY2ODE0YjU4M2M2NDI3MDA4NGJjNjhiMyJ9fX0="
      lore:
        - '§6Тут что-то ценное!'
        - ''
        - '§fЦена в голосах: §x§6§1§D§A§F§B1§x§2§D§9§1§F§F☆'
        - '§fБаланс голосов: §x§6§1§D§A§F§B{votes}§x§2§D§9§1§F§F☆'
        - '§7[Нажмите для покупки]'
    onBuyCommands: "minecraft:give {player} diamond"
  item2: # Пример как добавить стрелу со своим цветом и зачарованием
    price: 1
    icon:
      name: "&cУникальная стрела"
      material: tipped_arrow
      flags:
        - HIDE_POTION_EFFECTS
      glowing: true
      color:
        r: 255
        g: 1
        b: 1
      lore:
        - '&bКак попаду!'
        - ''
        - '§fЦена в голосах: §x§6§1§D§A§F§B1§x§2§D§9§1§F§F☆'
        - '§fБаланс голосов: §x§6§1§D§A§F§B{votes}§x§2§D§9§1§F§F☆'
        - '§7[Нажмите для покупки]'
    onBuyCommands: "minecraft:give {player} diamond"
  item3: # Пример как добавить зелье со своим цветом
    price: 1
    icon:
      name: "&cУникальная стрела"
      material: potion
      flags:
        - HIDE_POTION_EFFECTS
      color:
        r: 0
        g: 255
        b: 0
      lore:
        - '&6Какое-то зелье!'
        - ''
        - '§fЦена в голосах: §x§6§1§D§A§F§B1§x§2§D§9§1§F§F☆'
        - '§fБаланс голосов: §x§6§1§D§A§F§B{votes}§x§2§D§9§1§F§F☆'
        - '§7[Нажмите для покупки]'
    onBuyCommands: "minecraft:give {player} diamond"